spring.application.name=jetlagtracker
spring.datasource.url=jdbc:postgresql://localhost:5432/jetlag
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true